name: Build

on:
  pull_request:

jobs:
  build-without-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle (without testing)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x test -x integrationTest
